name = "gfstat"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSIONS"
id = "placeholder"
